services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: bb-postgres

    ports:
      - "5432:5432"
    restart: unless-stopped

    environment:
      POSTGRES_DB: blackbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa55word

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bb-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: bb-api
    build: .
    ports:
      - "8080:8080"
    restart: always

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bb-network

volumes:
  postgres_data:

networks:
  bb-network:
    driver: bridge
